
meta_product_name: "Swap My Dosh"
meta_title: "Swap My Dosh - Matching Travellers. Swapping Currencies. Zero Fees."
meta_description: "Swap My Dosh has cutting out currency conversion fees for travellers since 2018.  Established in Berlin by four avid travellers and coding gurus, Swap My Dosh allows you to match with travellers and exchange currencies for FREE. Get around the fees, become a Dosher today!"
meta_image: "SMDlogo.png"                       # should exist in `app/assets/images/`
twitter_account: "@swapmydosh" 